[WIP] mongo7 upgrade
kbase/catalog pull request #140
Opened 2024-12-17 22:50 UTC by Xiangs18

2025-01-23 17:11 UTC, bio-boris commented on test/mock_auth/server.py
> +catalog_mock_auth = ['auth_admin.json', 'auth_invalid.json', 'auth_missing.json', 'auth_non_admin.json']
It would be good to put a comment here explaining that the order is being preserved here in order to ensure the routes capture the requests in the correct order

2025-02-03 22:34 UTC, Xiangs18 commented on test/mock_auth/server.py
> +catalog_mock_auth = ['auth_admin.json', 'auth_invalid.json', 'auth_missing.json', 'auth_non_admin.json']
👍

2025-02-05 22:51 UTC, bio-boris commented on lib/biokbase/catalog/db.py
> +        self.index_created = defaultdict(int)
Should this be a bool?

2025-02-06 16:27 UTC, Xiangs18 commented on lib/biokbase/catalog/db.py
> +        self.index_created = defaultdict(int)
I used 1 for True and 0 for False.

2025-02-06 16:40 UTC, bio-boris commented on lib/biokbase/catalog/db.py
> +        self.index_created = defaultdict(int)
Yes, so why not use a defaultdict(bool) instead?

2025-02-06 21:14 UTC, Xiangs18 commented on lib/biokbase/catalog/db.py
> +        self.index_created = defaultdict(int)
👍

2025-02-06 21:29 UTC, Xiangs18 commented
This PR does the following:
1. Removed all submodules (jars, kbapi_common, nms).
2. Added the NMS Docker service for local testing.
3. Fixed a bug in mock_auth/servicer.py.
4. Updated the catalog Docker build script.
5. Implemented lazy loading for MongoDB.
6. Cleaned up files in the repository.

2025-02-06 21:56 UTC, bio-boris requested changes
The pr description is empty, and would benefit from a copy of the changelog/release notes . The version and release notes should be updated as well

2025-02-06 21:56 UTC, bio-boris commented on Makefile
> -init:
Does this init section need to be removed or can we keep it in?

2025-02-06 21:56 UTC, bio-boris commented on Makefile
> -	rsync -av kbapi_common/lib/biokbase/* $(TESTLIB)/biokbase/.
If we don't need this anymore, can we delete it instead of commenting it out?

2025-02-06 21:56 UTC, bio-boris commented on .github/workflows/test.yml
> +            - 27018:27017
Can we keep it at 27017?

2025-02-06 21:56 UTC, bio-boris commented on .github/workflows/test.yml
> +      - name: Install Docker Compose
This is not necessary. You can use `docker compose` as it is included in docker nowadays

2025-02-06 21:56 UTC, bio-boris commented on test/mock_auth/server.py
> +catalog_mock_auth = ['auth_admin.json', 'auth_invalid.json', 'auth_missing.json', 'auth_non_admin.json']
Not sure if a comment was added or not, but additional info about "Mock server servers matches routes in a specific order, this is the current order required for tests to pass"

2025-02-06 21:56 UTC, bio-boris commented on test/test.cfg.example
> +mongodb-host = localhost:27018
Can we keep this at 27017?

2025-02-06 21:56 UTC, bio-boris commented on lib/biokbase/catalog/db.py
> +        # Make sure we have a unique index on module_name_lc and git_commit_hash
It is possible to refactor this giant `elif` block using a dictionary to map collection names to their respective index creation functions. Here is an example of how you can refactor it:

```python
def _create_indexes(self, collection_name):
    """Create indexes for the given collection lazily."""
    collection = self.db[collection_name]

    index_creation_map = {
        MongoCatalogDBI._MODULE_VERSIONS: [
            ('module_name_lc', False),
            ('git_commit_hash', False),
            [('module_name_lc', ASCENDING), ('git_commit_hash', ASCENDING), True]
        ],
        MongoCatalogDBI._LOCAL_FUNCTIONS: [
            'function_id',
            [('module_name_lc', ASCENDING), ('function_id', ASCENDING), ('git_commit_hash', ASCENDING), True],
            'module_name_lc',
            'git_commit_hash'
        ],
        # Add other collections and their indexes similarly
    }

    indexes = index_creation_map.get(collection_name, [])
    for index in indexes:
        if isinstance(index, tuple):
            collection.create_index(index[0], sparse=index[1])
        elif isinstance(index, list):
            collection.create_index(index, unique=index[-1])
        else:
            collection.create_index(index)
```

This approach uses a dictionary to map collection names to a list of indexes, which reduces the need for multiple `elif` statements. Adjust the `index_creation_map` dictionary as needed to cover all your collections and their respective indexes.

2025-02-06 21:56 UTC, bio-boris commented on lib/biokbase/catalog/db.py
> +        """Create indexes for the given collection lazily."""
It might be better to move out these into smaller functions into a file or class like db_indexes.py or something as this is an extremely long function. If possible, function's shouldn't be longer than the entire height of your screen.

2025-02-06 21:56 UTC, bio-boris commented on lib/biokbase/catalog/db.py
> +            return
This is missing coverage

2025-02-06 21:56 UTC, bio-boris commented on lib/biokbase/catalog/db.py
> +        volume_mounts_collection = self.db[MongoCatalogDBI._VOLUME_MOUNTS]
I think this entire function can be deleted, as we have already upgraded the indexes?

2025-02-06 21:57 UTC, bio-boris commented on Makefile
> -init:
Or was this deprecated in favor of docker compose, and was only needed for tests?

2025-02-06 21:58 UTC, bio-boris commented on test/docker-compose_nms.yml
> +
Can we re-name this file as "docker-compose?"

2025-02-06 22:01 UTC, bio-boris commented
> This PR does the following:
> 
>     1. Removed all submodules (jars, kbapi_common, nms).
> 
>     2. Added the NMS Docker service for local testing.
> 
>     3. Fixed a bug in mock_auth/servicer.py.
> 
>     4. Updated the catalog Docker build script.
> 
>     5. Implemented lazy loading for MongoDB.
> 
>     6. Cleaned up files in the repository.

This also upgrades pymongo

I think these can be added to the README.md

2025-02-07 21:20 UTC, MrCreosote commented on lib/biokbase/catalog/db.py
> +        # Make sure we have a unique index on module_name_lc and git_commit_hash
You could potentially use an index spec to simplify as well: https://github.com/kbase/cdm-task-service/blob/main/cdmtaskservice/mongo.py#L70

2025-02-07 21:22 UTC, MrCreosote commented on test/docker-compose_nms.yml
> +
If this is a compose file for the nms rather than the catalog, calling it as such seems appropriate to me

2025-02-07 21:35 UTC, bio-boris commented on test/docker-compose_nms.yml
> +
It is a docker compose for testing purposes. By naming it "docker-compose" it allows you to start it up without specifying the path to a file. If we had multiple docker composes, I think it makes sense to use a non standard name, but since we only have one docker-compose file, we should use the standard name.

2025-02-07 22:04 UTC, Xiangs18 commented on Makefile
> -init:
because all submodules are removed.

2025-02-07 22:05 UTC, Xiangs18 commented on .github/workflows/test.yml
> +            - 27018:27017
port 27017 is already being used by the NMS Mongo

2025-02-07 22:06 UTC, Xiangs18 commented on test/test.cfg.example
> +mongodb-host = localhost:27018
port 27017 is already being used by the NMS Mongo

2025-02-07 22:12 UTC, MrCreosote commented on .github/workflows/test.yml
> +          echo "ADMIN_USER=$ADMIN_USER" >> $GITHUB_ENV
Could you add a comment about why this env var is set up and where it's used? That should help the next person who has to work on this service understand what's going on

2025-02-07 22:12 UTC, MrCreosote commented on Dockerfile
> +RUN pip install -r requirements.txt
We should convert to pipenv / poetry / uv, but that's a later task

2025-02-07 22:12 UTC, MrCreosote commented on lib/biokbase/log.py
Is this an exact copy from kb_sdk_plus?

2025-02-07 22:12 UTC, MrCreosote commented on test/run_tests.sh
> +docker run -d --rm -v ${PWD}/mock_auth:/config -v ${PWD}/mock_auth/server.py:/server/server.py -p 7777:5000 --name mock-auth mockservices/mock_json_service
This isn't something we need to deal with now, but there are plenty of 3rd party service mocking options out there, I'm not sure why we rolled our own. Also auth2 has test mode which we could use

2025-02-07 22:12 UTC, MrCreosote commented on test/run_tests.sh
> +curl -d '{"id":"1","params":[],"method":"NarrativeMethodStore.ver","version":"1.1"}' http://localhost:7125/rpc
Wow these tests must not've passed for a long time...

2025-02-07 22:12 UTC, MrCreosote commented on test/mock_auth/server.py
This file needs some explanation at the top. Why are we replacing the file in the mock server container? Whoever comes along next to work on the catalog will need to understand the reasoning behind this

2025-02-07 22:12 UTC, MrCreosote commented on test/mock_auth/server.py
What changes have been made in this file compared to the original in the mock server container?

2025-02-07 22:12 UTC, MrCreosote commented on lib/biokbase/catalog/db.py
> +        # MongoDB client and database initialization deferred
Can you add an explanation as to why this is necessary?

2025-02-07 22:12 UTC, MrCreosote commented on lib/biokbase/catalog/db.py
> +        # MongoDB client and database initialization deferred
How lazy is lazy? Is it not until a request is made, and therefore the service can be running in a guaranteed to fail state? If so, it seems like this class should at least test connectivity and auth at init time

2025-02-07 22:12 UTC, MrCreosote commented on lib/biokbase/catalog/db.py
> +                if self.mongo_user and self.mongo_psswd:
Can you add a note here that this case is only tested manually?

I assume it has been tested manually, yeah?

2025-02-07 22:12 UTC, MrCreosote commented on lib/biokbase/catalog/db.py
> +        # MongoDB client and database initialization deferred
IIUC the db class instance is created pre fork, and then the fork happens and it's no longer working. If that's the case, and if it's possible, what I would do is

* in the init, check connectivity, check db schema, create indexes, etc., and close the client.
* On the first call, create a mongo client knowing that everything is set up correctly, and set up the instance variables for the collections. Then you don't need all the property functions

2025-02-07 22:13 UTC, MrCreosote commented on .github/workflows/test.yml
> +            - 27018:27017
I would change the NMS port in that case. If one or the other is going to have non standard port it should be the supporting system, not the one we're working on

2025-02-07 22:14 UTC, MrCreosote commented on lib/biokbase/catalog/db.py
> +        volume_mounts_collection = self.db[MongoCatalogDBI._VOLUME_MOUNTS]
AFAIK we're the only ones using the catalog, all these db version changes happened years ago, and so we can just put a note in the release notes that db version upgrades are no longer supported and delete all the upgrade methods

2025-02-07 22:15 UTC, Xiangs18 commented on test/docker-compose_nms.yml
> +
It has nothing to do with testing the catalog service. It's just for starting the NMS service for CI/local testing to run unit tests. It makes more sense to keep its name as is.

2025-02-07 22:16 UTC, MrCreosote commented on test/docker-compose_nms.yml
> +
I'm fine with `-f <file>` in this case but I don't feel that strongly about it

2025-02-07 22:18 UTC, MrCreosote commented on lib/biokbase/catalog/db.py
> +        # MongoDB client and database initialization deferred
Oh, also you probably need a thread lock around the client creation step, or multiple calls could result in multiple client creations

2025-02-07 22:20 UTC, Xiangs18 commented on lib/biokbase/log.py
https://kbase.slack.com/archives/C05SSJT13BN/p1738107988928679?thread_ts=1738105198.145779&cid=C05SSJT13BN

2025-02-07 22:22 UTC, MrCreosote commented on lib/biokbase/log.py
yes, I'm aware of that post, but it doesn't answer the question

2025-02-07 22:50 UTC, Xiangs18 commented on lib/biokbase/log.py
yes, from https://github.com/kbase/kb_sdk_plus/blob/main/src/java/us/kbase/templates/log.py

2025-02-07 23:19 UTC, MrCreosote commented on lib/biokbase/log.py
:+1:

2025-02-07 23:22 UTC, bio-boris commented on .github/workflows/test.yml
> +            - 27018:27017
Why do we need 2 seperate mongos?

2025-02-07 23:24 UTC, MrCreosote commented on .github/workflows/test.yml
> +            - 27018:27017
One presumably starts up with the docker compose to support NMS, the other starts up as part of the catalog tests. That seems good to me, the catalog shouldn't know or care about any NMS dependencies

2025-02-07 23:59 UTC, Xiangs18 commented on Makefile
> -	rsync -av kbapi_common/lib/biokbase/* $(TESTLIB)/biokbase/.
removed

2025-02-08 00:06 UTC, Xiangs18 commented on .github/workflows/test.yml
> +      - name: Install Docker Compose
This step is necessary.

https://github.com/kbase/catalog/actions/runs/13210034758/job/36881655854?pr=140#step:6:43

2025-02-08 00:24 UTC, MrCreosote commented on .github/workflows/test.yml
> +      - name: Install Docker Compose
Try `docker compose` without the hyphen

2025-02-10 18:47 UTC, Xiangs18 commented on .github/workflows/test.yml
> +      - name: Install Docker Compose
👍

2025-02-10 19:53 UTC, Xiangs18 commented on test/test.cfg.example
> +mongodb-host = localhost:27018
👍

2025-02-10 19:54 UTC, Xiangs18 commented on .github/workflows/test.yml
> +            - 27018:27017
👍

2025-02-10 19:56 UTC, Xiangs18 commented on Dockerfile
> +RUN pip install -r requirements.txt
next PR

2025-02-10 20:01 UTC, bio-boris commented on .github/workflows/test.yml
> +            - 27018:27017
So the mongo in test.yml will be 27017 and the one in nms-compose.yaml will be 27018?

2025-02-10 20:11 UTC, Xiangs18 commented on .github/workflows/test.yml
> +            - 27018:27017
NMS will be mapped to port 27018, and Catalog will be mapped into port 27017.

2025-02-11 17:24 UTC, Xiangs18 commented on test/mock_auth/server.py
> +catalog_mock_auth = ['auth_admin.json', 'auth_invalid.json', 'auth_missing.json', 'auth_non_admin.json']
I did add a comment. For some reason, it is not showing up here, but you can see it in the changed files.

2025-02-11 17:34 UTC, Xiangs18 commented on .github/workflows/test.yml
> +          echo "ADMIN_USER=$ADMIN_USER" >> $GITHUB_ENV
Isn't line 84 doing what you're suggesting?

2025-02-11 18:00 UTC, bio-boris commented on test/mock_auth/server.py
> +catalog_mock_auth = ['auth_admin.json', 'auth_invalid.json', 'auth_missing.json', 'auth_non_admin.json']
I see "# The order is preserved here to ensure routes capture requests correctly." this is not very descriptive and not really telling the story of why this needs to be here.

2025-02-11 18:02 UTC, bio-boris commented on .github/workflows/test.yml
> +          echo "ADMIN_USER=$ADMIN_USER" >> $GITHUB_ENV
Is this section necessary? It seems like this variable is already being set in

```
        env:
          KBASE_CI_TOKEN: ${{ secrets.KBASE_CI_TOKEN }}
          ADMIN_USER: ${{ secrets.KBASE_BOT_USER_CI }}
```

2025-02-11 18:11 UTC, MrCreosote commented on .github/workflows/test.yml
> +          echo "ADMIN_USER=$ADMIN_USER" >> $GITHUB_ENV
> Isn't line 84 already addressing what you're suggesting,

On second look yes it is, I think I was thrown by the wording a bit. For me I think this would make it a little more clear:

" This env var is used in the catalog test docker compose file for starting NMS"

2025-02-11 18:12 UTC, MrCreosote commented on .github/workflows/test.yml
> +          echo "ADMIN_USER=$ADMIN_USER" >> $GITHUB_ENV
But maybe Boris is right and you could just set the env var in the test task rather than putting it in $GITHUB_ENV. Either way it needs explanation though

2025-02-11 18:14 UTC, bio-boris commented on .github/workflows/test.yml
> +            - 27018:27017
Looks like this was changed to 27017

2025-02-11 18:14 UTC, bio-boris commented on test/test.cfg.example
> +mongodb-host = localhost:27018
Looks like this was changed to 27017

2025-02-11 18:51 UTC, Xiangs18 commented on .github/workflows/test.yml
> +          echo "ADMIN_USER=$ADMIN_USER" >> $GITHUB_ENV
@bio-boris, are you saying that I can directly access ADMIN_USER from the docker-compose_nms.yml without passing it into $GITHUB_ENV, or are you suggesting that I can simply set ADMIN_USER in the docker-compose_nms.yml?

2025-02-11 19:05 UTC, bio-boris commented on .github/workflows/test.yml
> +          echo "ADMIN_USER=$ADMIN_USER" >> $GITHUB_ENV
Yes, you can access it without passing it into the github_env as you seem to be grabbing it from the github env

2025-02-11 21:02 UTC, Xiangs18 commented on .github/workflows/test.yml
> +          echo "ADMIN_USER=$ADMIN_USER" >> $GITHUB_ENV
@MrCreosote, comment added.
@bio-boris, I'm not exactly sure how I should set it up in test.yml. Do I need a global variable? Could you please provide an example?

2025-02-11 21:03 UTC, Xiangs18 commented on test/run_tests.sh
> +docker run -d --rm -v ${PWD}/mock_auth:/config -v ${PWD}/mock_auth/server.py:/server/server.py -p 7777:5000 --name mock-auth mockservices/mock_json_service
https://github.com/kbase/catalog/issues/143

2025-02-11 21:04 UTC, bio-boris commented on .github/workflows/test.yml
> +          echo "ADMIN_USER=$ADMIN_USER" >> $GITHUB_ENV
I don't understand. Isn't the environment variable already there?

2025-02-11 21:04 UTC, MrCreosote commented on .github/workflows/test.yml
> +          echo "ADMIN_USER=$ADMIN_USER" >> $GITHUB_ENV
You would just add the same env stanza from install dependencies to run tests

2025-02-11 21:06 UTC, bio-boris commented on .github/workflows/test.yml
> +          echo "ADMIN_USER=$ADMIN_USER" >> $GITHUB_ENV
Suggested cleanup:

    Remove echo "ADMIN_USER=$ADMIN_USER" – This doesn't provide additional value in the script.
    Remove echo "ADMIN_USER=$ADMIN_USER" >> $GITHUB_ENV – Since ADMIN_USER is already available as an environment variable in the env: block, explicitly adding it to $GITHUB_ENV is redundant.

2025-02-11 21:10 UTC, bio-boris commented on .github/workflows/test.yml
> +          echo "ADMIN_USER=$ADMIN_USER" >> $GITHUB_ENV
Oh I understand now. Yea, you could make it "global" by putting it at the "jobs" level

2025-02-11 21:34 UTC, Xiangs18 commented on .github/workflows/test.yml
> +          echo "ADMIN_USER=$ADMIN_USER" >> $GITHUB_ENV
Hi, I removed $GITHUB_ENV, and it's working now!

2025-02-11 21:49 UTC, bio-boris commented on .github/workflows/test.yml
> +          echo "ADMIN_USER=$ADMIN_USER" >> $GITHUB_ENV
LGTM!

2025-02-11 22:14 UTC, Xiangs18 commented on test/mock_auth/server.py
The only change is hardcoding the catalog_mock_auth sequence instead of using os.listdir(). Comment added.

2025-02-11 22:14 UTC, Xiangs18 commented on test/mock_auth/server.py
Comment added.

2025-02-11 22:15 UTC, Xiangs18 commented on test/mock_auth/server.py
> +catalog_mock_auth = ['auth_admin.json', 'auth_invalid.json', 'auth_missing.json', 'auth_non_admin.json']
Comment added. Please let me know if it makes sense now.

2025-02-11 22:20 UTC, bio-boris commented on test/mock_auth/server.py
> +catalog_mock_auth = ['auth_admin.json', 'auth_invalid.json', 'auth_missing.json', 'auth_non_admin.json']
LGTM!

2025-02-11 22:22 UTC, Xiangs18 commented on lib/biokbase/catalog/db.py
> +                if self.mongo_user and self.mongo_psswd:
Yes, simply initiating the class will cause this test to fail now. We need to trigger a function to lazily load MongoDB. Once I make a public call, the test passes.

https://github.com/kbase/catalog/blob/377f65108eea20bbbe4a9ac37fc15301ab484585/test/startup_test.py#L38-L44

2025-02-11 22:24 UTC, MrCreosote commented on lib/biokbase/catalog/db.py
> +                if self.mongo_user and self.mongo_psswd:
Did this comment go to the wrong place? It doesn't seem to have anything to do with the parent comment

2025-02-11 22:38 UTC, Xiangs18 commented on lib/biokbase/catalog/db.py
> +                if self.mongo_user and self.mongo_psswd:
> Can you add a note here that this case is only tested manually?

@MrCreosote, does `this case` refer to the entire function or just lines 141-143?

2025-02-11 22:42 UTC, MrCreosote commented on lib/biokbase/catalog/db.py
> +                if self.mongo_user and self.mongo_psswd:
Just the case where creds are provided

2025-02-11 22:50 UTC, Xiangs18 commented on lib/biokbase/catalog/db.py
> +        volume_mounts_collection = self.db[MongoCatalogDBI._VOLUME_MOUNTS]
@bio-boris, what does `entire function` refer to?

2025-02-11 23:21 UTC, Xiangs18 commented on lib/biokbase/catalog/db.py
> +        # MongoDB client and database initialization deferred
The explanation has been added.

2025-02-11 23:22 UTC, Xiangs18 commented on lib/biokbase/catalog/db.py
> +                if self.mongo_user and self.mongo_psswd:
Note added. It has only been manually tested.

2025-02-11 23:46 UTC, Xiangs18 commented on lib/biokbase/catalog/db.py
> +        volume_mounts_collection = self.db[MongoCatalogDBI._VOLUME_MOUNTS]
Also, why do we need to update the database schema to v4? I assume the `db version` here does not refer to the MongoDB version.

2025-02-11 23:49 UTC, Xiangs18 commented on Dockerfile
> +RUN pip install -r requirements.txt
https://github.com/kbase/catalog/issues/142

2025-02-12 03:31 UTC, bio-boris commented on lib/biokbase/catalog/db.py
> +        volume_mounts_collection = self.db[MongoCatalogDBI._VOLUME_MOUNTS]
update_db_3_to_4

2025-02-13 18:43 UTC, Xiangs18 commented on lib/biokbase/catalog/db.py
> +        volume_mounts_collection = self.db[MongoCatalogDBI._VOLUME_MOUNTS]
https://github.com/kbase/catalog/issues/144

2025-02-13 21:29 UTC, Xiangs18 commented on lib/biokbase/catalog/db.py
> +            return
I moved it into _initialize_mongo_client function.

2025-02-14 01:17 UTC, Xiangs18 commented on lib/biokbase/catalog/db.py
> +        """Create indexes for the given collection lazily."""
I moved into db_indexes.py

2025-02-14 01:17 UTC, Xiangs18 commented on lib/biokbase/catalog/db.py
> +        # Make sure we have a unique index on module_name_lc and git_commit_hash
Done

2025-02-14 01:39 UTC, Xiangs18 commented on lib/biokbase/catalog/db.py
> +        # MongoDB client and database initialization deferred
> How lazy is lazy?

I added more comments in this [commit](https://github.com/kbase/catalog/pull/140/commits/ae1b22445f28fc5a0705f36dc2dcc6cab1e936ba). If you have any further questions, please let me know.

Could you discuss the trade-offs between your design and the current implementation?

2025-02-14 01:43 UTC, MrCreosote commented on lib/biokbase/catalog/db.py
> +        # MongoDB client and database initialization deferred
The issue with the current implementation the service can start in a guaranteed to fail state. In what I propose above it can't.

2025-02-14 01:45 UTC, Xiangs18 commented on lib/biokbase/catalog/db.py
> +        # MongoDB client and database initialization deferred
What is guaranteed to fail state?

2025-02-14 03:58 UTC, MrCreosote commented on lib/biokbase/catalog/db.py
> +        # MongoDB client and database initialization deferred
It means that the server is up, but if anyone makes a call to it that needs to contact mongo, that call will fail

2025-02-14 04:45 UTC, Xiangs18 commented on lib/biokbase/catalog/db.py
> +        # MongoDB client and database initialization deferred
Why do you think that call will fail?

2025-02-14 05:49 UTC, MrCreosote commented on lib/biokbase/catalog/db.py
> +        # MongoDB client and database initialization deferred
Because the server is in a guaranteed to fail state.

2025-02-14 16:27 UTC, bio-boris commented on lib/biokbase/catalog/db.py
> +        # Get the indexes for the collection from the DBIndexes class
It seems that all of this code can go into the db_indexes.py code.

2025-02-14 16:28 UTC, bio-boris commented on lib/biokbase/catalog/db.py
> +        """Create indexes for the given collection lazily."""
Why are the indexes created lazily instead of upon first starting the app?

2025-02-14 16:30 UTC, bio-boris commented on lib/biokbase/catalog/db.py
> +        """Create indexes for the given collection lazily."""
I think it is better to create them when the app starts. After that you could then remove
```
        if not self.index_created[collection_name]:
            self._create_indexes(collection_name)
            self.index_created[collection_name] = True
```
From the  _initialize_mongo_client code

2025-02-14 16:34 UTC, bio-boris commented on test/mock_auth/server.py
I don't see an explanation added here at the top as per the request that explains why we are replacing this file in the mock server container.

2025-02-14 17:09 UTC, Xiangs18 commented on lib/biokbase/catalog/db.py
> +        # Get the indexes for the collection from the DBIndexes class
It can. However, it makes more sense to me that in db_indexes.py, we first retrieve the indexes, and then the code to create the indexes is underneath the _create_indexes function.

2025-02-14 17:19 UTC, Xiangs18 commented on lib/biokbase/catalog/db.py
> +        # Get the indexes for the collection from the DBIndexes class
You mean line 242?

2025-02-14 17:33 UTC, Xiangs18 commented on lib/biokbase/catalog/db.py
> +        # Get the indexes for the collection from the DBIndexes class
If you mean the entire process, it makes more sense to me to separate the steps of getting and creating indexes.

2025-02-14 18:10 UTC, bio-boris commented on lib/biokbase/catalog/db.py
> +        # Get the indexes for the collection from the DBIndexes class
I agree. What I am suggesting is the code that creates the indexes be encapsulated in the DBIndexes class

2025-02-14 18:36 UTC, Xiangs18 commented on lib/biokbase/catalog/db.py
> +        """Create indexes for the given collection lazily."""
Because when we start the app and create collections/indexes in __init__, it would encounter the MongoClient opened before fork issue.

2025-02-14 18:38 UTC, Xiangs18 commented on lib/biokbase/catalog/db.py
> +        # Get the indexes for the collection from the DBIndexes class
Does it look better now?

2025-02-14 18:51 UTC, bio-boris commented on lib/biokbase/catalog/db.py
> +        """Create indexes for the given collection lazily."""
What about creating them before the uswgi process is started up?

2025-02-14 19:10 UTC, bio-boris commented on lib/biokbase/catalog/db_indexes.py
> +from pymongo import ASCENDING
It seems a bit strange to create indexes based on a specific collection name being rather than just create them in one go.

Here's one way to do it
```
from pymongo import ASCENDING
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

class DBIndexes:
    _INDEX_MAP = {
        "module_versions": [
            {"fields": ["module_name_lc"], "unique": False, "sparse": False},
            {"fields": ["git_commit_hash"], "unique": False, "sparse": False},
            {"fields": ["module_name_lc", "git_commit_hash"], "unique": True, "sparse": False},
        ],
        "local_functions": [
            {"fields": ["function_id"], "unique": False, "sparse": False},
            {"fields": ["module_name_lc"], "unique": False, "sparse": False},
            {"fields": ["git_commit_hash"], "unique": False, "sparse": False},
            {"fields": ["module_name_lc", "function_id", "git_commit_hash"], "unique": True, "sparse": False},
        ],
        "developers": [
            {"fields": ["kb_username"], "unique": True, "sparse": False},
        ],
        "build_logs": [
            {"fields": ["registration_id"], "unique": True, "sparse": False},
            {"fields": ["module_name_lc"], "unique": False, "sparse": False},
            {"fields": ["timestamp"], "unique": False, "sparse": False},
            {"fields": ["registration"], "unique": False, "sparse": False},
            {"fields": ["git_url"], "unique": False, "sparse": False},
            {"fields": ["current_versions.release.release_timestamp"], "unique": False, "sparse": False},
        ],
        "favorites": [
            {"fields": ["user"], "unique": False, "sparse": False},
            {"fields": ["module_name_lc"], "unique": False, "sparse": False},
            {"fields": ["id"], "unique": False, "sparse": False},
            {"fields": ["user", "id", "module_name_lc"], "unique": True, "sparse": False},
        ],
        "exec_stats_raw": [
            {"fields": ["user_id"], "unique": False, "sparse": False},
            {"fields": ["app_module_name", "app_id"], "unique": False, "sparse": True},
            {"fields": ["func_module_name", "func_name"], "unique": False, "sparse": True},
            {"fields": ["creation_time"], "unique": False, "sparse": False},
            {"fields": ["finish_time"], "unique": False, "sparse": False},
        ],
        "exec_stats_apps": [
            {"fields": ["module_name"], "unique": False, "sparse": True},
            {"fields": ["full_app_id", "type", "time_range"], "unique": True, "sparse": False},
            {"fields": ["type", "time_range"], "unique": False, "sparse": True},
        ],
        "exec_stats_users": [
            {"fields": ["user_id", "type", "time_range"], "unique": True, "sparse": False},
        ],
        "client_groups": [
            {"fields": ["module_name_lc", "function_name"], "unique": True, "sparse": False},
        ],
        "volume_mounts": [
            {"fields": ["client_group", "module_name_lc", "function_name"], "unique": True, "sparse": False},
        ],
        "secure_config_params": [
            {"fields": ["module_name_lc"], "unique": False, "sparse": False},
            {"fields": ["module_name_lc", "version", "param_name"], "unique": True, "sparse": False},
        ],
    }

    @classmethod
    def get_indexes(cls, collection_name):
        return cls._INDEX_MAP.get(collection_name, [])

    @staticmethod
    def create_indexes(collection, indexes):
        index_definitions = [
            {
                "key": [(field, ASCENDING) for field in index["fields"]],
                "unique": index.get("unique", False),
                "sparse": index.get("sparse", False),
            }
            for index in indexes
        ]
        
        collection.create_indexes(index_definitions)
        logger.info(f"Created indexes: {index_definitions}")

```

2025-02-14 19:43 UTC, bio-boris commented on lib/biokbase/catalog/db_indexes.py
> +from pymongo import ASCENDING
I forget, why did this code even get changed to this instead of keeping the original code?

2025-02-14 20:12 UTC, bio-boris commented on lib/biokbase/catalog/db_indexes.py
> +from pymongo import ASCENDING
https://github.com/kbase/catalog/commit/ec3064b8115f12021fc903d852d1eb41fef0ff8b Looks like the code was fine before but a bunch of else ifs were added

2025-02-14 20:14 UTC, bio-boris commented on lib/biokbase/catalog/db_indexes.py
> +from pymongo import ASCENDING
It did everything in one go, rather than doing things by a specific collection.

2025-02-14 22:36 UTC, Xiangs18 commented on lib/biokbase/catalog/db_indexes.py
> +from pymongo import ASCENDING
The original Mongo initialization is in __init__, and it created the collection/index in a single operation. When we switched to lazy Mongo loading, the collection/index was created only on their first call, which is why there are multiple 'elif' statements.

Now we are switching to https://github.com/kbase/catalog/pull/140#discussion_r1947256110

2025-02-15 00:08 UTC, Xiangs18 commented on test/mock_auth/server.py
done

2025-02-15 01:09 UTC, bio-boris commented on lib/biokbase/catalog/db_indexes.py
> +from pymongo import ASCENDING
I think keeping in the "declarative" and straightforward style that it was before would make this code less confusing. In addition, this can be run as a script before the server starts up.

2025-02-18 21:37 UTC, Xiangs18 commented on lib/biokbase/catalog/db.py
> +        # MongoDB client and database initialization deferred
> On the first call, create a mongo client knowing that everything is set up correctly, and set up the instance variables for the collections. Then you don't need all the property functions

Here, without the property functions, how/where do we get the first call?

2025-02-18 21:45 UTC, MrCreosote commented on lib/biokbase/catalog/db.py
> +        # MongoDB client and database initialization deferred
I'm  not sure I understand the question, but you get the first call when some process makes an HTTP request to the service.

2025-02-18 22:05 UTC, Xiangs18 commented on lib/biokbase/catalog/db.py
> +        # MongoDB client and database initialization deferred
Hi @bio-boris, Gavin and I were discussing this thread: https://github.com/kbase/catalog/pull/140#discussion_r1960626709. Do you have a preference for property functions, or should we add an `ensure_mongo_client_connect function/decorator` to each API method in db.py?

2025-02-19 01:21 UTC, Xiangs18 commented on lib/biokbase/catalog/db.py
> +        # MongoDB client and database initialization deferred
@MrCreosote, I used a decorator, but I'm not sure why I'm getting `pymongo.errors.InvalidOperation: Cannot use MongoClient after close.` I might try making a manual call in each function instead.

2025-02-19 01:33 UTC, MrCreosote commented on lib/biokbase/catalog/db.py
> +        # MongoDB client and database initialization deferred
It sounds like your client creation function is closing the client when it's done

2025-02-19 21:30 UTC, Xiangs18 commented on lib/biokbase/catalog/db.py
> +        # MongoDB client and database initialization deferred
I only manually closed it at the end of `__init__`, not during the client creation function.
https://github.com/kbase/catalog/blob/1f6024a3d6b9b084b005f72b50bf2325d1154f52/lib/biokbase/catalog/db.py#L158

2025-02-19 21:42 UTC, MrCreosote commented on lib/biokbase/catalog/db.py
> +        # MongoDB client and database initialization deferred
Well, the error is telling you it's closed, so either the error is wrong or the client is getting closed

2025-02-19 21:42 UTC, MrCreosote commented on lib/biokbase/catalog/db.py
> +        # MongoDB client and database initialization deferred
Or the wrong client is being used

2025-02-21 19:14 UTC, Xiangs18 commented on lib/biokbase/catalog/db.py
> +        # MongoDB client and database initialization deferred
The code seems to work fine in IPython during the __init__ step. I'm not sure why it is causing problems when I reinitialize it after the fork.

2025-02-21 19:15 UTC, MrCreosote commented on lib/biokbase/catalog/db.py
> +        # MongoDB client and database initialization deferred
What about calling methods post init?

2025-02-21 22:41 UTC, Xiangs18 commented on lib/biokbase/catalog/db.py
> +        # MongoDB client and database initialization deferred
https://kbase.slack.com/archives/C05SSJT13BN/p1740172424557279?thread_ts=1740165659.495869&cid=C05SSJT13BN
fixed, tested, and deployed to ci

2025-02-21 22:43 UTC, Xiangs18 commented on lib/biokbase/catalog/db.py
> +        # Get the indexes for the collection from the DBIndexes class
no more `elif`. Call _create_indexes function in `__init__`

2025-02-21 22:43 UTC, Xiangs18 commented on lib/biokbase/catalog/db_indexes.py
> +from pymongo import ASCENDING
Call _create_indexes function in __init__

2025-02-21 22:55 UTC, MrCreosote commented on Dockerfile
> +RUN pip install -r requirements.txt
:+1:

2025-02-21 22:56 UTC, MrCreosote commented on test/run_tests.sh
> +docker run -d --rm -v ${PWD}/mock_auth:/config -v ${PWD}/mock_auth/server.py:/server/server.py -p 7777:5000 --name mock-auth mockservices/mock_json_service
:+1:

2025-02-21 22:59 UTC, MrCreosote commented on .github/workflows/test.yml
> +          echo "ADMIN_USER=$ADMIN_USER" >> $GITHUB_ENV
:+1:

2025-02-21 23:09 UTC, MrCreosote commented on test/mock_auth/server.py
:+1:

2025-02-21 23:10 UTC, MrCreosote commented on lib/biokbase/catalog/db.py
> +        # MongoDB client and database initialization deferred
:+1:

2025-02-21 23:10 UTC, MrCreosote commented on test/mock_auth/server.py
:+1:

2025-02-21 23:28 UTC, bio-boris commented on lib/biokbase/catalog/db_indexes.py
> +from pymongo import ASCENDING
I don't understand what you are saying.

2025-02-21 23:29 UTC, bio-boris commented on lib/biokbase/catalog/db.py
> +        # Get the indexes for the collection from the DBIndexes class
I think the original way it looked was much better.

2025-02-21 23:39 UTC, MrCreosote commented on lib/biokbase/catalog/db.py
> +        # MongoDB client and database initialization deferred
I would expound on the explanation - the user may not understand why and when forking is happening

2025-02-21 23:39 UTC, MrCreosote commented on lib/biokbase/catalog/db.py
> +        # MongoDB client and database initialization deferred
:+1:

2025-02-21 23:40 UTC, MrCreosote commented on lib/biokbase/catalog/db.py
> +                if self.mongo_user and self.mongo_psswd:
:+1:

2025-02-21 23:50 UTC, MrCreosote commented on lib/biokbase/catalog/db.py
> +        self.lock = threading.Lock()
I was concerned about how the fork would affect the lock object, so I asked chatgpt. It thinks that it'll be fine if it's created at the module level, so let's do that. TBH its explanations of why doing it in init is bad were pretty vague but it's probably cleaner than in the class init anyway.

2025-02-21 23:50 UTC, MrCreosote commented on lib/biokbase/catalog/db.py
> +        self.client_initialized = False
I think you can just check whether the mongo client is None or not, the extra boolean is redundant

2025-02-21 23:50 UTC, MrCreosote commented on lib/biokbase/catalog/db.py
> +        self._initialize_mongo_client()
To be safe, I would avoid creating any mongo releated instance variables in the init function, as that could cause bugs in the future if someone doesn't deal with re-initing the client correctly. Have the init mongo method return the client and then pass it to the db schema, indexes, and close method

2025-02-21 23:50 UTC, MrCreosote commented on Dockerfile
> +RUN apt-get update && apt-get install -y rsync
Can you note that the rysnc install is needed for the Makefile?

Or update the makefile to not need it, up to you

2025-02-21 23:50 UTC, MrCreosote commented on Makefile
>  #	rsync -av narrative_method_store/lib/biokbase/* $(TESTLIB)/biokbase/.
Might as well remove these comments as well

2025-02-21 23:50 UTC, MrCreosote commented on test/docker-compose_nms.yml
> +      - method_spec_admin_users=${ADMIN_USER}
how do you expect a dev to deal with this when testing locally?

2025-02-21 23:50 UTC, MrCreosote commented on lib/biokbase/catalog/db.py
> +                if not self.client_initialized or self.mongo_client is None:
```suggestion
        """Initialize MongoDB client with lock to prevent race conditions."""
        # Use the lock to ensure only one thread initializes the mongo client at a time
        if self.mongo_client:
            return
        with self.lock:
            try:
                if not self.client_initialized or self.mongo_client is None:
```

Don't even pay the cost of entering the lock if the client is available

2025-02-21 23:50 UTC, MrCreosote commented on lib/biokbase/catalog/db.py
>      def find_basic_module_info(self, query):
I think this blank line should stay, the above comment applies to many methods, not just this one

2025-02-21 23:50 UTC, MrCreosote commented on lib/biokbase/catalog/db.py
> -
I think this blank line should stay, the above comment applies to many methods, not just this one

2025-02-22 00:02 UTC, Xiangs18 commented on lib/biokbase/catalog/db_indexes.py
> +from pymongo import ASCENDING
There is no longer a db_indexes.py file. This thread is no longer relevant.

2025-02-22 00:06 UTC, Xiangs18 commented on lib/biokbase/catalog/db.py
> +        # Get the indexes for the collection from the DBIndexes class
We are reverting to the previous method because lazy Mongo load is no longer needed. It is done.

https://github.com/kbase/catalog/blob/dev-mongo7_upgrade/lib/biokbase/catalog/db.py#L210

2025-02-24 21:58 UTC, Xiangs18 commented on lib/biokbase/catalog/db.py
> +        self.lock = threading.Lock()
👍

2025-02-24 21:58 UTC, Xiangs18 commented on lib/biokbase/catalog/db.py
> +        self.client_initialized = False
👍

2025-02-24 21:59 UTC, Xiangs18 commented on Dockerfile
> +RUN apt-get update && apt-get install -y rsync
added a comment

2025-02-24 21:59 UTC, Xiangs18 commented on Makefile
>  #	rsync -av narrative_method_store/lib/biokbase/* $(TESTLIB)/biokbase/.
👍

2025-02-24 21:59 UTC, Xiangs18 commented on lib/biokbase/catalog/db.py
> +                if not self.client_initialized or self.mongo_client is None:
👍

2025-02-24 21:59 UTC, Xiangs18 commented on lib/biokbase/catalog/db.py
>      def find_basic_module_info(self, query):
👍

2025-02-24 21:59 UTC, Xiangs18 commented on lib/biokbase/catalog/db.py
> -
👍

2025-02-24 22:16 UTC, Xiangs18 commented on test/docker-compose_nms.yml
> +      - method_spec_admin_users=${ADMIN_USER}
For testing locally,  either export the variable directly in the shell, or hardcode an admin user in the YAML file.

2025-02-24 22:23 UTC, MrCreosote commented on test/docker-compose_nms.yml
> +      - method_spec_admin_users=${ADMIN_USER}
How would a local dev know to do that?

2025-02-24 23:01 UTC, Xiangs18 commented on lib/biokbase/catalog/db.py
> +        self._initialize_mongo_client()
I see you want to pass the client handle around to be safe. 
What should be returned if the client is already initialized? Should we always return a new client?

```
    def _initialize_mongo_client(self):
        """Initialize MongoDB client with lock to prevent race conditions."""
        if self.client_initialized:
            return
```

2025-02-24 23:05 UTC, MrCreosote commented on lib/biokbase/catalog/db.py
> +        self._initialize_mongo_client()
It can't be initialized since we're in the init method.

2025-02-24 23:11 UTC, Xiangs18 commented on lib/biokbase/catalog/db.py
> +        self._initialize_mongo_client()
why it can be initialized before? And you recommended that check before going to the lock.

2025-02-24 23:18 UTC, MrCreosote commented on lib/biokbase/catalog/db.py
> +        self._initialize_mongo_client()
I can't be initialized before, it's in the init, which is run before any other method.

The check is for post fork, when there's no need to enter the lock if the client is available.

2025-02-25 20:28 UTC, Xiangs18 commented
<img width="1170" alt="Screenshot 2025-02-25 at 12 28 20 PM" src="https://github.com/user-attachments/assets/ba561841-8820-469d-9b4a-7ffacc7247f0" />

2025-02-25 20:29 UTC, Xiangs18 commented on test/docker-compose_nms.yml
> +      - method_spec_admin_users=${ADMIN_USER}
added a comment

2025-02-25 20:30 UTC, Xiangs18 commented on lib/biokbase/catalog/db.py
> +        self._initialize_mongo_client()
fixed, deployed, and tested in CI
https://github.com/kbase/catalog/pull/140#issuecomment-2683212105

2025-02-25 21:09 UTC, MrCreosote commented on Dockerfile
> +RUN apt-get update && apt-get install -y rsync
:+1:

2025-02-25 21:09 UTC, MrCreosote commented on Makefile
>  #	rsync -av narrative_method_store/lib/biokbase/* $(TESTLIB)/biokbase/.
:+1:

2025-02-25 21:09 UTC, MrCreosote commented on lib/biokbase/catalog/db.py
> +        self.lock = threading.Lock()
:+1:

2025-02-25 21:11 UTC, MrCreosote commented on lib/biokbase/catalog/db.py
> +        self.client_initialized = False
:+1:

2025-02-25 21:11 UTC, MrCreosote commented on lib/biokbase/catalog/db.py
>      def find_basic_module_info(self, query):
:+1:

2025-02-25 21:11 UTC, MrCreosote commented on lib/biokbase/catalog/db.py
> -
:+1:

2025-02-25 21:16 UTC, MrCreosote commented on test/docker-compose_nms.yml
> +      - method_spec_admin_users=${ADMIN_USER}
The first time dev is still going to have a hard time figuring out why the tests don't pass when they run them. Put yourself in their shoes - if you were running the tests for the first time, what would happen if you didn't know about this env var and how easy would it be to debug? How would you want this to work / be documented?

2025-02-25 21:31 UTC, MrCreosote commented on lib/biokbase/catalog/db.py
> +                if not self.client_initialized or self.mongo_client is None:
:+1:

2025-02-25 21:31 UTC, MrCreosote commented on lib/biokbase/catalog/db.py
> +        self._initialize_mongo_client()
:+1:

2025-02-25 21:35 UTC, MrCreosote commented on lib/biokbase/catalog/db.py
> +            raise ValueError(error_msg)
```suggestion
        except ConnectionFailure as e:
            raise ValueError(f"Cannot connect to Mongo server: {e}") from e
```

2025-02-25 21:35 UTC, MrCreosote commented on lib/biokbase/catalog/db.py
> +        # Use the lock to ensure only one thread initializes the mongo client at a time
I think this comment is in the wrong place

2025-02-25 21:35 UTC, MrCreosote commented on lib/biokbase/catalog/db.py
>              release_version_list = []
Why can't we delete all these upgrade methods again?

2025-02-25 22:06 UTC, Xiangs18 commented on lib/biokbase/catalog/db.py
> +        # MongoDB client and database initialization deferred
This conversation is irrelevant as we are not using lazy Mongo load anymore.

2025-02-25 22:10 UTC, MrCreosote commented on lib/biokbase/catalog/db.py
> +        # MongoDB client and database initialization deferred
We most certainly are. We're doing 2 mongo creations - a creation on init and a lazy creation after fork. The explanation for why we're doing that is totally relevant

2025-02-26 20:13 UTC, Xiangs18 commented on lib/biokbase/catalog/db.py
> +        # Use the lock to ensure only one thread initializes the mongo client at a time
👍

2025-02-26 20:13 UTC, Xiangs18 commented on lib/biokbase/catalog/db.py
> +            raise ValueError(error_msg)
👍

2025-02-26 20:14 UTC, Xiangs18 commented on lib/biokbase/catalog/db.py
>              release_version_list = []
https://kbase.slack.com/archives/C05SSJT13BN/p1739471119225879?thread_ts=1739292839.872669&cid=C05SSJT13BN

https://kbase.slack.com/archives/C05SSJT13BN/p1739471521100149?thread_ts=1739292839.872669&cid=C05SSJT13BN

2025-02-26 20:15 UTC, Xiangs18 commented on test/docker-compose_nms.yml
> +      - method_spec_admin_users=${ADMIN_USER}
I have updated it. Let me know if this is clearer this time.

2025-02-26 20:16 UTC, MrCreosote commented on lib/biokbase/catalog/db.py
>              release_version_list = []
Ok, so the answer is that when you remove them tests start failing. Can you make an issue in that case?

2025-02-26 20:29 UTC, Xiangs18 commented on lib/biokbase/catalog/db.py
>              release_version_list = []
https://github.com/kbase/catalog/pull/140#discussion_r1955046184

2025-02-26 20:30 UTC, MrCreosote commented on lib/biokbase/catalog/db.py
> +        # Use the lock to ensure only one thread initializes the mongo client at a time
:+1:

2025-02-26 20:30 UTC, MrCreosote commented on lib/biokbase/catalog/db.py
> +            raise ValueError(error_msg)
:+1:

2025-02-26 20:32 UTC, MrCreosote commented on test/docker-compose_nms.yml
> +      - method_spec_admin_users=${ADMIN_USER}
So again, I'm going to ask you to put yourself in the shoes of a first time developer running the tests. What will that developer see? What will they have to do to figure out what's wrong? How can we make it easier for them?

2025-02-26 20:35 UTC, MrCreosote commented on lib/biokbase/catalog/db.py
>              release_version_list = []
Oh great, forgot about that. :+1:

2025-02-26 23:50 UTC, Xiangs18 commented on test/docker-compose_nms.yml
> +      - method_spec_admin_users=${ADMIN_USER}
Maybe place the comments at the top of the docker-compose.yml file and add a comment in the [NarrativeMethodStore] section of the test.cfg.example file as well.

If you have something else in mind, please let me know.

2025-02-26 23:58 UTC, MrCreosote commented on test/docker-compose_nms.yml
> +      - method_spec_admin_users=${ADMIN_USER}
I don't have anything particular in mind because I don't understand the repercussions of not having the env var set.

Let me ask this - if a new dev runs the tests without the env var set, what will happen? What error message will they see?

2025-02-27 00:21 UTC, Xiangs18 commented on test/docker-compose_nms.yml
> +      - method_spec_admin_users=${ADMIN_USER}
It will basically explain that the value set by the developer in method-spec-admin-users under the [NarrativeMethodStore] section of the test.cfg.example file is not a global admin, as shown below. Once a new developer sets that parameter in the docker-compose_nms.yml file, as instructed in my comment, this error will be resolved.

<img width="1293" alt="Screenshot 2025-02-26 at 4 14 12 PM" src="https://github.com/user-attachments/assets/0bddb0bf-3df2-4eaa-9ae6-2f226b25ab86" />

2025-02-27 00:44 UTC, MrCreosote commented on test/docker-compose_nms.yml
> +      - method_spec_admin_users=${ADMIN_USER}
> developer in method-spec-admin-users under the [NarrativeMethodStore] section of the test.cfg

Ok, so looking at test.cfg.example, the user there is wstester4, so they'll get that message but with wstester4 instead of sijiex, right?

So how would they even know to look in the docker-compose_nms.yml file?

2025-02-27 01:18 UTC, Xiangs18 commented on test/docker-compose_nms.yml
> +      - method_spec_admin_users=${ADMIN_USER}
I just ran through some experiments, and what I found is that the nms-admin-token provided by the developer in test.cfg must match what they set in the docker-compose_nms.yml file. So, essentially, when they set the nms-admin-token in test.cfg, we can add step 4) to set the corresponding method_spec_admin_users parameter in the docker-compose_nms.yml file under the # TO RUN TESTS: section.

2025-02-27 01:20 UTC, Xiangs18 commented on test/docker-compose_nms.yml
> +      - method_spec_admin_users=${ADMIN_USER}
<img width="974" alt="Screenshot 2025-02-26 at 5 20 06 PM" src="https://github.com/user-attachments/assets/ae2dcd75-7515-4e67-9a66-d353bb41f8bd" />

2025-02-27 01:24 UTC, MrCreosote commented on test/docker-compose_nms.yml
> +      - method_spec_admin_users=${ADMIN_USER}
That sounds reasonable. The other things I would do are:

* Get rid of the references to username / password in the TO RUN TESTS section, those no longer exist.
* Put a short section in the readme, prior to the change log, telling the user how to run tests. This is probably just something like "read the instructions at the top of test/test.cfg.example"
* Now that there's a docker compose file, is the NarrativeMethodStore section in the test cfg even used? If not it should be deleted.

2025-02-28 00:29 UTC, Xiangs18 commented on test/docker-compose_nms.yml
> +      - method_spec_admin_users=${ADMIN_USER}
Do we even need 2)? It's already set by default to mongodb-host = localhost:27017.

2025-02-28 00:33 UTC, MrCreosote commented on test/docker-compose_nms.yml
> +      - method_spec_admin_users=${ADMIN_USER}
if the tests automatically start up mongo at that url sounds like no

2025-02-28 00:54 UTC, Xiangs18 commented on test/docker-compose_nms.yml
> +      - method_spec_admin_users=${ADMIN_USER}
👍

2025-02-28 01:31 UTC, Xiangs18 commented on lib/biokbase/catalog/db.py
> +        # MongoDB client and database initialization deferred
👍

2025-02-28 19:53 UTC, MrCreosote commented on test/docker-compose_nms.yml
> +      - method_spec_admin_users=${ADMIN_USER}
:

2025-02-28 19:53 UTC, MrCreosote commented on test/docker-compose_nms.yml
> +      - method_spec_admin_users=${ADMIN_USER}
:+1:

2025-02-28 19:53 UTC, MrCreosote commented on lib/biokbase/catalog/db.py
> +        # MongoDB client and database initialization deferred
:+1:

2025-02-28 19:54 UTC, MrCreosote commented
Note to self: all of my comments are addressed at this point

2025-02-28 20:21 UTC, MrCreosote commented on test/docker-compose_nms.yml
> +      - method_spec_mongo_host=mongo:27017
```suggestion
      - method_spec_mongo_host=mongo:27018
```

2025-02-28 20:21 UTC, MrCreosote commented on test/docker-compose_nms.yml
> +      - "tcp://mongo:27017"
```suggestion
      - "tcp://mongo:27018"
```

2025-02-28 20:21 UTC, MrCreosote commented on test/catalog_test_util.py
> +        self.mongo.drop_database('method_store_repo_db')
This is dropping a database in the catalog mongo db, not the one started up via the docker compose file. Does this run after every test or only at the end of the test suite? If the latter, I don't think it's needed since run_tests.sh does a `docker compose down`. If it is this file will need to set up a mongo client specifically for the NMS.

2025-02-28 20:21 UTC, MrCreosote commented on lib/biokbase/catalog/db.py
> +        # connections are not fork-safe. When a process is forked, the child process inherits a copy of the parent’s memory,
```suggestion
        # connections are not fork-safe and some servers, including uwsgi, fork workers from parent processes.
        # When a process is forked, the child process inherits a copy of the parent’s memory,
```

2025-02-28 20:21 UTC, MrCreosote commented on lib/biokbase/catalog/db.py
> +        exec_stats_apps_colleciton.update_many({'avg_queue_time': {'$exists': True}},
This looks like a C&P error

2025-02-28 20:21 UTC, MrCreosote commented on lib/biokbase/catalog/db.py
> +        exec_stats_apps_colleciton.update_many({'avg_queue_time': {'$exists': True}},
```suggestion
        exec_stats_apps_collection = db[MongoCatalogDBI._EXEC_STATS_APPS]
        exec_stats_apps_collection.update_many({'avg_queue_time': {'$exists': True}},
```

2025-02-28 20:21 UTC, MrCreosote commented on lib/biokbase/catalog/db.py
> +        exec_stats_apps_colleciton.update_many({'avg_queue_time': {'$exists': True}},
Can you run through the changes here one more time and ensure there aren't any other errors like this, where the collection is switched (assuming I'm understanding this correctly)

2025-02-28 20:49 UTC, Xiangs18 commented on lib/biokbase/catalog/db.py
> +        exec_stats_apps_colleciton.update_many({'avg_queue_time': {'$exists': True}},
Is this conversation the same as [this](https://github.com/kbase/catalog/pull/140#discussion_r1975967554)? Also, the suggested change you mentioned doesn't indicate anything different.

2025-02-28 21:01 UTC, MrCreosote commented on lib/biokbase/catalog/db.py
> +        exec_stats_apps_colleciton.update_many({'avg_queue_time': {'$exists': True}},
I'm not sure what you're talking about, this is just a spelling correction

2025-02-28 21:40 UTC, Xiangs18 commented on test/catalog_test_util.py
> +        self.mongo.drop_database('method_store_repo_db')
This is indeed dropping a database in the catalog MongoDB. But why would it be placed under the [NarrativeMethodStore] section?

The tearDown class method is run at the end of each test file, so I'm not 100% sure of its intention, as it could go either way. Dropping a database in the catalog MongoDB makes more sense to me because the catalog MongoDB handle was set up in the init helper method.

If that's the case, I would suggest deleting comments L230-231 and moving method_spec_mongo_dbname under the [catalog-test] section, unless you have a different perspective.

2025-02-28 21:48 UTC, Xiangs18 commented on lib/biokbase/catalog/db.py
> +        exec_stats_apps_colleciton.update_many({'avg_queue_time': {'$exists': True}},
fixed!

2025-02-28 21:48 UTC, Xiangs18 commented on lib/biokbase/catalog/db.py
> +        exec_stats_apps_colleciton.update_many({'avg_queue_time': {'$exists': True}},
👍

2025-02-28 21:48 UTC, Xiangs18 commented on lib/biokbase/catalog/db.py
> +        # connections are not fork-safe. When a process is forked, the child process inherits a copy of the parent’s memory,
👍

2025-02-28 22:01 UTC, Xiangs18 commented on test/docker-compose_nms.yml
> +      - method_spec_mongo_host=mongo:27017
The MongoDB container still listens on port 27017 internally, and the port mapping 27018:27017 already does the job. Therefore, no changes should be made here.

2025-02-28 22:01 UTC, Xiangs18 commented on test/docker-compose_nms.yml
> +      - "tcp://mongo:27017"
The MongoDB container still listens on port 27017 internally, and the port mapping 27018:27017 already does the job. Therefore, no changes should be made here.

2025-02-28 22:14 UTC, MrCreosote commented on lib/biokbase/catalog/db.py
> +        exec_stats_apps_colleciton.update_many({'avg_queue_time': {'$exists': True}},
Does that mean you double checked all the collection changes where `self` was removed?

2025-02-28 22:15 UTC, MrCreosote commented on lib/biokbase/catalog/db.py
> +        # connections are not fork-safe. When a process is forked, the child process inherits a copy of the parent’s memory,
:+1:

2025-02-28 22:15 UTC, MrCreosote commented on lib/biokbase/catalog/db.py
> +        exec_stats_apps_colleciton.update_many({'avg_queue_time': {'$exists': True}},
:+1:

2025-02-28 22:24 UTC, MrCreosote commented on test/docker-compose_nms.yml
> +      - method_spec_mongo_host=mongo:27017
Huh, I didn't realize until now that the connections were made internally in the containers, not via the port mapping. However, that means the database deletion below doesn't make any sense

2025-02-28 22:27 UTC, MrCreosote commented on test/catalog_test_util.py
> +        self.mongo.drop_database('method_store_repo_db')
> But why would it be placed under the [NarrativeMethodStore] section?

Because is the name of the NMS database, I presume.

> Dropping a database in the catalog MongoDB makes more sense to me because the catalog MongoDB handle was set up in the init helper method.

I'm not understanding the argument here - IIUC, the original code dropped the NMS database for the NMS server. At that point, the NMS and catalog shared a Mongo instance. Now they have separate instances and so dropping the NMS database from the catalog's mongo does nothing, because there's nothing to drop. The NMS database is now on the Mongo instance started by the docker compose file, and so needs to be dropped in that Mongo instance.

Am I missing something here?

2025-02-28 22:57 UTC, Xiangs18 commented on lib/biokbase/catalog/db.py
> +        exec_stats_apps_colleciton.update_many({'avg_queue_time': {'$exists': True}},
yes, I did

2025-02-28 23:08 UTC, MrCreosote commented on lib/biokbase/catalog/db.py
> +        exec_stats_apps_colleciton.update_many({'avg_queue_time': {'$exists': True}},
:+1:

2025-03-01 01:05 UTC, Xiangs18 commented on test/catalog_test_util.py
> +        self.mongo.drop_database('method_store_repo_db')
> make sure NMS is clean after each test

Yeah, this comment confirms that it's actually deleting the database from the NMS.

2025-03-01 01:05 UTC, Xiangs18 commented on test/catalog_test_util.py
> +        self.mongo.drop_database('method_store_repo_db')
👍

2025-03-03 20:47 UTC, MrCreosote commented on test/docker-compose_nms.yml
> +      - method_spec_mongo_host=mongo:27017
:+1:

2025-03-03 20:47 UTC, MrCreosote commented on test/docker-compose_nms.yml
> +      - "tcp://mongo:27017"
:+1:

2025-03-03 20:48 UTC, MrCreosote commented on test/catalog_test_util.py
> +        self.mongo.drop_database('method_store_repo_db')
:+1:

2025-03-03 20:49 UTC, MrCreosote reviewed
This LGTM, but @bio-boris should review / approve

2025-03-03 21:04 UTC, bio-boris approved these changes
Looks good enough to me to merge. We should remove uswgi from the dockerfile in the next PR i think

2025-03-03 21:04 UTC, bio-boris commented on Dockerfile
> +RUN apt-get update && apt-get install -y wget uwsgi
Does `uswgi` need to be installed here? We already have it in the requirements.txt

2025-03-03 21:04 UTC, bio-boris commented on lib/biokbase/catalog/db.py
> +        self.mongo_authMechanism = mongo_authMechanism
This should be _ case and not camelCase in order to maintain consistency

2025-03-03 21:14 UTC, Xiangs18 commented on lib/biokbase/catalog/db.py
> +        self.mongo_authMechanism = mongo_authMechanism
It will be addressed in the next PR.

2025-03-03 21:14 UTC, Xiangs18 commented on Dockerfile
> +RUN apt-get update && apt-get install -y wget uwsgi
It will be addressed in the next PR.

2025-03-03 21:17 UTC, merged

2025-03-03 23:56 UTC, Xiangs18 commented on Dockerfile
> +RUN apt-get update && apt-get install -y wget uwsgi
https://github.com/kbase/catalog/pull/145